# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod "ReactiveCocoa"
pod "Spark-SDK"

target 'Tempest' do

end

target 'TempestTests' do

end

target 'TempestUITests' do

end

